/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://3zcrl5f5pbechkgllzrtpujwym.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-x6gd4m2zcvhvxkszhmg3oquatm",
    "aws_cognito_identity_pool_id": "ap-south-1:1ee78fc4-656e-4595-9dc1-4d6abecb3be3",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_Gd51bWUak",
    "aws_user_pools_web_client_id": "379s9q8hrvp28qoa6nfpbdrmt1",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "mygateguardstoragebucket164059-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
